image: registry.gitlab.e.foundation/e/os/docker-android-apps-cicd:55-workshop-auto-release

variables:
  SENTRY_DSN: $SENTRY_DSN

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew


cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

# Debug build related jobs

dummy:
  stage: test
  only:
    - /^.*playground.*$/
  script:
    - echo "dummy job running $CI_COMMIT_REF_NAME! $CI_COMMIT_BRANCH"

dummy_job:
  stage: testJob
  only:
    variables:
      - $CI_COMMIT_MESSAGE = /^.*dummy.*$/
  script:
    - echo "second dummy job running $CI_COMMIT_MESSAGE"

test:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
  script:
    - echo "Test run Started!"
    - ./gradlew test
    - echo "Test running ended!"
  artifacts:
    when: always
    paths:
      - app/build/test-results/*/TEST-*.xml
      - app/build/reports/tests/*
    reports:
      junit: app/build/test-results/*/TEST-*.xml

lint:
  stage: build
  script:
    - ./gradlew lintRelease
    - echo "lint fininshed"

after_script:
  - echo "after script is executed"