image: "registry.gitlab.e.foundation:5000/e/apps/docker-android-apps-cicd:latest"

stages:
  - debug
  - release

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

# Debug build related jobs
buildDebug:
  stage: debug
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/

# Default lint configuration for debug builds
# Manual as we don't want to run them generally for debug builds
.lintDebugDefault:
  stage: debug
  when: manual
  allow_failure: true

lintDebug:
  extends: .lintDebugDefault
  script:
    - ./gradlew lintDebug
  artifacts:
    paths:
      - app/build/reports/

ktlintDebug:
  extends: .lintDebugDefault
  script:
    - ./gradlew app:ktlintCheck --info
  artifacts:
    paths:
      - app/build/reports/ktlint/

# Release build related jobs

# Default configuration for release builds
# Only on "master" and "merge_request_event"
.releaseDefault:
  stage: release
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

buildRelease:
  extends: .releaseDefault
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/

lintRelease:
  extends: .releaseDefault
  script:
    - ./gradlew lintRelease
  artifacts:
    paths:
      - app/build/reports/

ktlintRelease:
  extends: .releaseDefault
  script:
    - ./gradlew app:ktlintCheck --info
  artifacts:
    paths:
      - app/build/reports/ktlint/
