image: "registry.gitlab.e.foundation:5000/e/apps/docker-android-apps-cicd:latest"

stages:
- build

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

build-without-auto-install:
  stage: build
  script:
  - ./gradlew build
  artifacts:
    paths:
    - app/build/outputs/apk/

build:
  extends: build-without-auto-install
  script:
  - git apply auto-install.patch
  - ./gradlew build
  