image: "registry.gitlab.e.foundation:5000/e/apps/docker-android-apps-cicd:latest"

stages:
- build

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

build:
  stage: build
  script:
  - ./gradlew build
  artifacts:
    paths:
    - app/build/outputs/apk/
    - app/build/reports/