[versions]
activityKtx = "1.10.0"
androidGradlePlugin = "8.8.0"
appcompat = "1.7.0"
bcpgJdk15on = "1.60"
coil = "1.4.0"
constraintlayout = "2.2.0"
core = "1.6.1"
coreKtx = "1.15.0"
coreTesting = "2.2.0"
datastorePreferences = "1.1.2"
elib = "0.0.1-alpha11"
espressoCore = "3.6.1"
hiltCompiler = "1.2.0"
hiltWork = "1.2.0"
lifecycleExtensions = "1.1.1"
fragmentKtx = "1.8.5"
gplayapi = "3.4.5-0"
gson = "2.11.0"
jacksonDataformatYaml = "2.17.0"
jsoup = "1.17.2"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlin = "2.1.0"
hilt = "2.54"
kotlinxCoroutinesAndroid = "1.10.1"
ksp = "2.1.0-1.0.29"
legacySupportV4 = "1.0.0"
lifecycleViewmodelKtx = "2.8.7"
loggingInterceptor = "4.11.0"
material = "1.12.0"
mockitoCore = "5.14.2"
mockitoInline = "5.0.0"
mockitoKotlin = "5.4.0"
mockk = "1.12.3"
moshiKotlin = "1.15.1"
detekt = "1.23.7"
ktlint = "10.2.0"
navigation = "2.8.5"
okhttp = "4.12.0"
photoview = "2.3.0"
preferenceKtx = "1.2.1"
protobufJavalite = "4.28.2"
room = "2.6.1"
shimmer = "0.5.0"
telemetry = "0.0.11-alpha"
timber = "5.0.1"
truth = "1.1.4"
viewpager2 = "1.1.0"
recyclerview = "1.4.0"
workRuntimeKtx = "2.10.0"

[libraries]
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
bcpg-jdk15on = { module = "org.bouncycastle:bcpg-jdk15on", version.ref = "bcpgJdk15on" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "gson" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "gson" }
converter-jackson = { module = "com.squareup.retrofit2:converter-jackson", version.ref = "gson" }
core = { module = "androidx.test:core", version.ref = "core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
elib = { module = "foundation.e:elib", version.ref = "elib" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
lifecycle-extensions = { module = "android.arch.lifecycle:extensions", version.ref = "lifecycleExtensions" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
gplayapi = { module = "foundation.e:gplayapi", version.ref = "gplayapi" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt"}
hilt-compile = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt"}
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jacksonDataformatYaml" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesAndroid" }
legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleViewmodelKtx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleViewmodelKtx" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlin" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
photoview = { module = "com.github.Baseflow:PhotoView", version.ref = "photoview" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobufJavalite" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "gson" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
telemetry = { module = "foundation.e.lib:telemetry", version.ref = "telemetry" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-plugin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigation" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
